### ISSUE TITLE
[pwdguess] Clarify what must be part of the hand-in

### ISSUE THREAD

**Issue by lenfra** [OpenSecEd/passwd#16]
In \subsection{Introductory reflection} students miss the part 
"Start by comparing how long a password consisting of lower- and upper-case letters, numbers and special characters must be to have the same strength as a password consisting of three and four randomly chooses words, respectively."

Possible need to reformulate the question?

**Comment by dbosk** [comment]
Or make it more clear in the end what should be part of the report?

**Comment by dbosk** [comment]
Maybe we did this. It seems quite clear at the end that it should be part of the hand-in.
